# Generated by Django 4.2.7 on 2023-12-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_data_change_product_date_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='описание отсутствует', verbose_name='описание'),
        ),
    ]
