# Generated by Django 4.2.7 on 2023-12-05 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_data_change_product_date_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateField(default=datetime.date(2023, 12, 6), verbose_name='дата создания'),
        ),
    ]
